### ISSUE TITLE
How would you handle inline HTML formatting?

### ISSUE THREAD

**Issue by oytuntez** [tokenmill/accelerated-text#326]
Hi everyone,

We have a case where we generate a large chunk of text, a few paragraphs, and we need some formatting in HTML format. We currently simply entered the HTML tags/CSS rules inside the text in AccText... :( it really doesn't feel good to do that...

A typical formatted text looks like this on AccText:
![image](https://user-images.githubusercontent.com/656635/117958083-58349380-b323-11eb-91af-bc611c528b1c.png)

And here is a sample output:
![image](https://user-images.githubusercontent.com/656635/117958184-726e7180-b323-11eb-9d9b-7618f87c7e0d.png)

You can see the inline formatting in blue/green phrases.

How would you handle this? The only thing that comes to my mind is to use transformers/enrichers (which @zmedelis reminded me in issue #324).

**Comment by zmedelis** [comment]
Hi, was thinking about how to do this, since AT does not support this directly. [Annotated text](https://accelerated-text.readthedocs.io/en/latest/graphql/) data structure returns text in segments: paragraphs, sentences, words. The best would be to introduce additional structural elements here. Still at the UI level, one would need to indicate that this thing is a link or part of a bullet list.

I'll post here further plans on this.

**Comment by rokasramas** [comment]
@oytuntez, you can try defining AMR structures for this: https://accelerated-text.readthedocs.io/en/latest/amr/
in this case, they might look something similar:
![Screenshot from 2021-06-30 16-02-55](https://user-images.githubusercontent.com/20424394/123965744-6ca91a00-d9bd-11eb-9aea-799d1071be49.png)
![Screenshot from 2021-06-30 16-03-04](https://user-images.githubusercontent.com/20424394/123965748-6d41b080-d9bd-11eb-8a76-edfd36a97b60.png)
![Screenshot from 2021-06-30 16-03-14](https://user-images.githubusercontent.com/20424394/123965749-6dda4700-d9bd-11eb-8b53-2ac17b747f0e.png)
